{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tomorrow.uicomponent",
    "module": "ListDisplay",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "ListDisplay-1.0.0.aar",
          "url": "ListDisplay-1.0.0.aar",
          "size": 104217,
          "sha512": "439bbced774aa6b94a142fc28c3781d2e1e39e8ce4da3045e97b2c62467be046d8569ce71dee003f7fc344e568c0a1978daf0a39931e85e623ea9d37b018bef2",
          "sha256": "4df4312045139797584fb5df1852324b215d8b6c6a90ae32ab09835000c8d427",
          "sha1": "99ddbbc83dbd4a72fe4cdaedffa219fe90889919",
          "md5": "416d6716abd4d703f63b66d14d6a13a2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.tomorrow.uicomponent",
          "module": "components",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.tomorrow.uicomponent",
          "module": "ReadViewModel",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.compose.compiler",
          "module": "compiler",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "ListDisplay-1.0.0.aar",
          "url": "ListDisplay-1.0.0.aar",
          "size": 104217,
          "sha512": "439bbced774aa6b94a142fc28c3781d2e1e39e8ce4da3045e97b2c62467be046d8569ce71dee003f7fc344e568c0a1978daf0a39931e85e623ea9d37b018bef2",
          "sha256": "4df4312045139797584fb5df1852324b215d8b6c6a90ae32ab09835000c8d427",
          "sha1": "99ddbbc83dbd4a72fe4cdaedffa219fe90889919",
          "md5": "416d6716abd4d703f63b66d14d6a13a2"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ListDisplay-1.0.0-sources.jar",
          "url": "ListDisplay-1.0.0-sources.jar",
          "size": 8469,
          "sha512": "98c48d10beb5566bca1574172f66aaa7fa932d3e5275d4f9fa3a85bf8fb00bd24413659252ada28069a992be8812c96a590a9bb364d1b925c84de31ef9664e4c",
          "sha256": "2740778f56fef3c4d11789a6440eb00668919f08a5f8934650235052f0bbd755",
          "sha1": "2413880f23bb5df79c75902afe0fb9ed3bd90543",
          "md5": "fb970b80a6810e283e642343ac01fcf0"
        }
      ]
    }
  ]
}
