{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tomorrow.uicomponent",
    "module": "components",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "components-1.0.0.aar",
          "url": "components-1.0.0.aar",
          "size": 399694,
          "sha512": "5153c3f0c35c1a18e32f3aa24f5443873347654e481c6f697f72584c87702eb0baad5c6b25ebc3b165b5a50a24fe424701f1dbaf18ffe0f50244099407f1b2ba",
          "sha256": "c1d6daa914bd0bbb703ee604ca3d6713dea9a00949ffea42b03a9e988f39f165",
          "sha1": "3680c527f44ec934957f6cf6c5e4e44240acc1e1",
          "md5": "dc001cd614c4f8991ae9492899836bdf"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.compose.compiler",
          "module": "compiler",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "components-1.0.0.aar",
          "url": "components-1.0.0.aar",
          "size": 399694,
          "sha512": "5153c3f0c35c1a18e32f3aa24f5443873347654e481c6f697f72584c87702eb0baad5c6b25ebc3b165b5a50a24fe424701f1dbaf18ffe0f50244099407f1b2ba",
          "sha256": "c1d6daa914bd0bbb703ee604ca3d6713dea9a00949ffea42b03a9e988f39f165",
          "sha1": "3680c527f44ec934957f6cf6c5e4e44240acc1e1",
          "md5": "dc001cd614c4f8991ae9492899836bdf"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "components-1.0.0-sources.jar",
          "url": "components-1.0.0-sources.jar",
          "size": 61361,
          "sha512": "2f4af53b9a7b0fb93b607c09d2b42cee9a998b47c91be4137d849f73c344c1cdfd1698193025fd41624e0830f06776742ea49839bfe1b774fee4ec51d73bae21",
          "sha256": "8ca4ab9315808b03d6d78e5f86149fe9cf3e2582e890031b3285d56f9cfc7328",
          "sha1": "b372c99d3a9cff78527e37b85d30bda15be6c0b8",
          "md5": "74dbd37c514ec642bee0d26d3897aa12"
        }
      ]
    }
  ]
}
