{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tomorrow.uicomponent",
    "module": "ReadViewModel",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "ReadViewModel-1.0.0.aar",
          "url": "ReadViewModel-1.0.0.aar",
          "size": 47346,
          "sha512": "e676cc78047366b6b4dbbd0bdc579c39e877b494ea37386b030bd83841aac77d29f3254e47f86771cafa2fa97fd3a4c1367fbf3b6358a59c195e54fe8968483d",
          "sha256": "1ff73234048ab7f6b9889e4d2e2f0fe8c7d3520b307c082c82c57dc30aab804a",
          "sha1": "d1337b21944f408a684a1c0407cc9fb43c353872",
          "md5": "2d5216f1e67cc3f5f9da1f34aaa50840"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.tomorrow.uicomponent",
          "module": "components",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.compose.compiler",
          "module": "compiler",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "ReadViewModel-1.0.0.aar",
          "url": "ReadViewModel-1.0.0.aar",
          "size": 47346,
          "sha512": "e676cc78047366b6b4dbbd0bdc579c39e877b494ea37386b030bd83841aac77d29f3254e47f86771cafa2fa97fd3a4c1367fbf3b6358a59c195e54fe8968483d",
          "sha256": "1ff73234048ab7f6b9889e4d2e2f0fe8c7d3520b307c082c82c57dc30aab804a",
          "sha1": "d1337b21944f408a684a1c0407cc9fb43c353872",
          "md5": "2d5216f1e67cc3f5f9da1f34aaa50840"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ReadViewModel-1.0.0-sources.jar",
          "url": "ReadViewModel-1.0.0-sources.jar",
          "size": 4829,
          "sha512": "ba65d353b0f4c426c741ea5a39aa23c39bbc54d7216140e2ea4fe97129aaf3f605769adf12b777152d7a56c4248809e15f160ec2b944509330a36e070b16b68b",
          "sha256": "67e7acbdcc707e6e724a0d74449bcfc8c4f22e90a568a5427bfb769aae18c80b",
          "sha1": "7503998ecc49d9125cce18a223817b07ace84f71",
          "md5": "a37ccdbcd9c256dbb73f34310c0a4aa0"
        }
      ]
    }
  ]
}
